const sampleListings = [
  // --- Residential ---
  {
    title: "Serene 3BHK Apartment in Bandra",
    description: "A beautifully furnished 3BHK apartment in the heart of Bandra, Mumbai. Offers stunning city views and is close to cafes and boutiques.",
    image: [
      { url: "https://a0.muscache.com/im/pictures/miso/Hosting-853979493557853158/original/9d30001a-6415-4303-9b63-4735166a1a1f.jpeg?im_w=1200", filename: "listing1_1.webp" },
      { url: "https://a0.muscache.com/im/pictures/miso/Hosting-853979493557853158/original/42618d43-5566-4c6e-a612-259160e15998.jpeg?im_w=720", filename: "listing1_2.webp" },
    ],
    price: 35000,
    location: "Mumbai",
    country: "India",
    purpose: "Rent",
    usage: "Residential",
    propertyType: "Apartment",
    residential: { size: 1800, furnishing: "Furnished", amenities: ["Gym", "Security", "Parking"] },
  },
  {
    title: "Luxury Villa with Private Pool",
    description: "An exquisite villa in Lonavala with a private infinity pool and a lush garden. Perfect for a luxurious weekend getaway.",
    image: [
        { url: "https://a0.muscache.com/im/pictures/miso/Hosting-53395995/original/6c29d0a7-23a5-47d3-a81e-69d659773721.jpeg?im_w=1200", filename: "listing2_1.webp" },
        { url: "https://a0.muscache.com/im/pictures/miso/Hosting-53395995/original/c6d22263-4416-4993-8461-a488733221c6.jpeg?im_w=720", filename: "listing2_2.webp" },
    ],
    price: 25000,
    location: "Lonavala",
    country: "India",
    purpose: "Rent",
    usage: "Residential",
    propertyType: "Villa",
    residential: { size: 4000, furnishing: "Furnished", amenities: ["Pool", "Kitchen", "WiFi"] },
  },
  {
    title: "Spacious Family Home for Sale",
    description: "A large independent house in a prime residential area of South Delhi, perfect for a growing family. Features a private garden and ample parking.",
    image: [
        { url: "https://a0.muscache.com/im/pictures/3831873/2679822a_original.jpg?im_w=1200", filename: "listing3_1.webp" },
        { url: "https://a0.muscache.com/im/pictures/3831885/c8a2b536_original.jpg?im_w=720", filename: "listing3_2.webp" },
    ],
    price: 45000000,
    location: "Delhi",
    country: "India",
    purpose: "Sell",
    usage: "Residential",
    propertyType: "Independent House",
    residential: { size: 3200, furnishing: "Semi-Furnished", amenities: ["Parking", "Security"] },
  },
  {
    title: "Historic Villa in Tuscany",
    description: "Experience the charm of Tuscany in this beautifully restored villa. Explore the rolling hills and vineyards.",
    image: [
      { url: "https://images.unsplash.com/photo-1566073771259-6a8506099945?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8aG90ZWxzfGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60", filename: "listing4_1.webp" },
    ],
    price: 2500,
    location: "Florence",
    country: "Italy",
    purpose: "Rent",
    usage: "Residential",
    propertyType: "Villa",
    residential: { size: 3500, furnishing: "Furnished", amenities: ["Pool", "Parking", "Kitchen"] },
  },
  {
    title: "Modern Loft in Downtown NYC",
    description: "Stay in the heart of the city in this stylish loft apartment. Perfect for urban explorers!",
    image: [
      { url: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTh8fHRyYXZlbHxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60", filename: "listing5_1.webp" },
    ],
    price: 1800000,
    location: "New York City",
    country: "United States",
    purpose: "Sell",
    usage: "Residential",
    propertyType: "Apartment",
    residential: { size: 950, furnishing: "Semi-Furnished", amenities: ["Gym", "Security"] },
  },
  // --- Commercial ---
  {
    title: "Premium Office Space in BKC",
    description: "A-grade commercial office space in Mumbai's Bandra Kurla Complex. Ideal for corporate headquarters.",
    image: [
      { url: "https://images.unsplash.com/photo-1521737604893-d14cc237f11d?q=80&w=2940&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D", filename: "listing6_1.webp" },
    ],
    price: 250000,
    location: "Mumbai",
    country: "India",
    purpose: "Rent",
    usage: "Commercial",
    propertyType: "Office",
    commercial: { size: 5000, parkingSpaces: 20, amenities: ["Central AC", "Elevator", "Power Backup"] },
  },
  {
    title: "Retail Shop on Main Street",
    description: "High-traffic retail shop available for long-term lease in a bustling commercial area of Pune.",
    image: [
      { url: "https://images.unsplash.com/photo-1441986300917-64674bd600d8?q=80&w=2940&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D", filename: "listing7_1.webp" },
    ],
    price: 80000,
    location: "Pune",
    country: "India",
    purpose: "Rent",
    usage: "Commercial",
    propertyType: "Shop",
    commercial: { size: 800, parkingSpaces: 2, amenities: ["Security"] },
  },
  {
    title: "Large Warehouse for Sale",
    description: "Expansive warehouse facility with high ceilings and multiple loading docks. Located in an industrial park with excellent connectivity.",
    image: [
      { url: "https://images.unsplash.com/photo-1587293852726-70cdb1e8586b?q=80&w=2940&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D", filename: "listing8_1.webp" },
    ],
    price: 80000000,
    location: "Ahmedabad",
    country: "India",
    purpose: "Sell",
    usage: "Commercial",
    propertyType: "Warehouse",
    commercial: { size: 20000, parkingSpaces: 50, amenities: ["Power Backup"] },
  },
  // --- Hospitality ---
  {
    title: "Boutique Hotel in Jaipur",
    description: "Charming boutique hotel reflecting the heritage of the Pink City. Offers a rooftop restaurant with fort views.",
    image: [
      { url: "https://images.unsplash.com/photo-1564501049412-61c2a3083791?q=80&w=2832&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D", filename: "listing9_1.webp" },
    ],
    price: 7000,
    location: "Jaipur",
    country: "India",
    purpose: "Rent",
    usage: "Hospitality",
    propertyType: "Hotel",
    hospitality: { rooms: 25, starRating: 4, amenities: ["Restaurant", "Pool", "WiFi"] },
  },
  {
    title: "Himalayan Mountain Resort",
    description: "A serene resort nestled in the Himalayas near Manali. Offers trekking, spa services, and stunning valley views.",
    image: [
      { url: "https://images.unsplash.com/photo-1582719508461-905c673771fd?q=80&w=2825&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D", filename: "listing10_1.webp" },
    ],
    price: 12000,
    location: "Manali",
    country: "India",
    purpose: "Rent",
    usage: "Hospitality",
    propertyType: "Resort",
    hospitality: { rooms: 50, starRating: 5, amenities: ["Restaurant", "Bar", "Gym"] },
  },
  {
    title: "Cozy Backpacker Hostel",
    description: "A vibrant and friendly hostel in the heart of Rishikesh, perfect for solo travelers and adventure seekers.",
    image: [
      { url: "https://images.unsplash.com/photo-1522992319-35816d38e027?q=80&w=2787&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D", filename: "listing11_1.webp" },
    ],
    price: 800,
    location: "Rishikesh",
    country: "India",
    purpose: "Rent",
    usage: "Hospitality",
    propertyType: "Hostel",
    hospitality: { rooms: 15, starRating: 3, amenities: ["WiFi", "Kitchen"] },
  },
  // --- Land & Other ---
  {
    title: "Residential Plot for Sale",
    description: "A prime residential plot in a gated community in Hyderabad, ready for construction. All approvals in place.",
    image: [
      { url: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?q=80&w=2940&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D", filename: "listing12_1.webp" },
    ],
    price: 12000000,
    location: "Hyderabad",
    country: "India",
    purpose: "Sell",
    usage: "Land/Other",
    propertyType: "Plot",
    land: { plotSize: 2400, plotUnit: "sqft" },
  },
  {
    title: "Vast Agricultural Land",
    description: "15 acres of fertile agricultural land near Nashik, suitable for vineyards and farming. Includes a farmhouse.",
    image: [
      { url: "https://images.unsplash.com/photo-1444930694458-01bab732b857?q=80&w=2940&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D", filename: "listing13_1.webp" },
    ],
    price: 20000000,
    location: "Nashik",
    country: "India",
    purpose: "Sell",
    usage: "Land/Other",
    propertyType: "Agricultural Land",
    land: { plotSize: 15, plotUnit: "acre" },
  },
  // ... Add even more listings here to make it 30+
  {
    title: "Ski-In/Ski-Out Chalet",
    description: "Hit the slopes right from your doorstep in this ski-in/ski-out chalet in the Swiss Alps.",
    image: [
      { url: "https://images.unsplash.com/photo-1502784444187-359ac186c5bb?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTJ8fHNreSUyMHZhY2F0aW9ufGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60", filename: "listing14_1.webp" },
    ],
    price: 3000,
    location: "Verbier",
    country: "Switzerland",
    purpose: "Rent",
    usage: "Residential",
    propertyType: "Villa",
    residential: { size: 2200, furnishing: "Furnished", amenities: ["Kitchen", "WiFi"] },
  },
  {
    title: "Charming Cottage in the Cotswolds",
    description: "Escape to the picturesque Cotswolds in this quaint and charming cottage with a thatched roof.",
    image: [
      { url: "https://images.unsplash.com/photo-1602088113235-229c19758e9f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8YmVhY2glMjB2YWNhdGlvbnxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60", filename: "listing15_1.webp" },
    ],
    price: 1200,
    location: "Cotswolds",
    country: "United Kingdom",
    purpose: "Rent",
    usage: "Residential",
    propertyType: "Independent House",
    residential: { size: 1500, furnishing: "Furnished", amenities: ["Parking", "Kitchen"] },
  },
  {
    title: "Modern Apartment in Tokyo",
    description: "Explore the vibrant city of Tokyo from this modern and centrally located apartment.",
    image: [
      { url: "https://images.unsplash.com/photo-1480796927426-f609979314bd?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTV8fHRva3lvfGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60", filename: "listing16_1.webp" },
    ],
    price: 2000,
    location: "Tokyo",
    country: "Japan",
    purpose: "Rent",
    usage: "Residential",
    propertyType: "Apartment",
    residential: { size: 700, furnishing: "Furnished", amenities: ["WiFi", "Security"] },
  },
  {
    title: "Luxury Penthouse with City Views",
    description: "Indulge in luxury living with panoramic city views from this stunning penthouse apartment.",
    image: [
      { url: "https://images.unsplash.com/photo-1622396481328-9b1b78cdd9fd?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8c2t5JTIwdmFjYXRpb258ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=800&q=60", filename: "listing17_1.webp" },
    ],
    price: 3500,
    location: "Los Angeles",
    country: "United States",
    purpose: "Rent",
    usage: "Residential",
    propertyType: "Apartment",
    residential: { size: 2800, furnishing: "Furnished", amenities: ["Pool", "Gym", "Parking"] },
  },
  {
    title: "Beachfront Bungalow in Bali",
    description: "Relax on the sandy shores of Bali in this beautiful beachfront bungalow with a private pool.",
    image: [
      { url: "https://images.unsplash.com/photo-1602391833977-358a52198938?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MzJ8fGNhbXBpbmd8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=800&q=60", filename: "listing18_1.webp" },
    ],
    price: 1800,
    location: "Bali",
    country: "Indonesia",
    purpose: "Rent",
    usage: "Residential",
    propertyType: "Independent House",
    residential: { size: 1600, furnishing: "Furnished", amenities: ["Pool", "WiFi"] },
  },
  {
    title: "Art Deco Apartment in Miami",
    description: "Step into the glamour of the 1920s in this stylish Art Deco apartment in South Beach.",
    image: [
      { url: "https://plus.unsplash.com/premium_photo-1670963964797-942df1804579?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTZ8fGxvZGdlfGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60", filename: "listing19_1.webp" },
    ],
    price: 1600,
    location: "Miami",
    country: "United States",
    purpose: "Rent",
    usage: "Residential",
    propertyType: "Apartment",
    residential: { size: 1100, furnishing: "Furnished", amenities: ["Pool", "Security"] },
  },
  {
    title: "Historic Castle in Scotland",
    description: "Live like royalty in this historic castle in the Scottish Highlands. Explore the rugged beauty of the area.",
    image: [
      { url: "https://images.unsplash.com/photo-1585543805890-6051f7829f98?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTl8fGJlYWNoJTIwdmFjYXRpb258ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=800&q=60", filename: "listing20_1.webp" },
    ],
    price: 4000,
    location: "Scottish Highlands",
    country: "United Kingdom",
    purpose: "Rent",
    usage: "Hospitality",
    propertyType: "Hotel",
    hospitality: { rooms: 10, starRating: 5, amenities: ["Restaurant"] },
  },
  {
    title: "Desert Oasis in Dubai",
    description: "Experience luxury in the middle of the desert in this opulent oasis in Dubai with a private pool.",
    image: [
      { url: "https://images.unsplash.com/photo-1518684079-3c830dcef090?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8ZHViYWl8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=800&q=60", filename: "listing21_1.webp" },
    ],
    price: 5000,
    location: "Dubai",
    country: "United Arab Emirates",
    purpose: "Rent",
    usage: "Residential",
    propertyType: "Villa",
    residential: { size: 5000, furnishing: "Furnished", amenities: ["Pool", "Gym"] },
  },
  {
    title: "Co-working Space in Koramangala",
    description: "Flexible and dedicated desks available in a premium co-working space in the heart of Bangalore's startup hub.",
    image: [
      { url: "https://images.unsplash.com/photo-1552664730-d307ca884978?q=80&w=2940&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D", filename: "listing22_1.webp" },
    ],
    price: 15000,
    location: "Bangalore",
    country: "India",
    purpose: "Rent",
    usage: "Land/Other",
    propertyType: "Co-working",
    commercial: { size: 3000, amenities: ["WiFi", "Power Backup", "Central AC"] },
  },
  {
    title: "Sea-Facing Showroom for Sale",
    description: "A premium showroom space on Marine Drive, Mumbai, offering unmatched visibility and prestige. Perfect for luxury brands.",
    image: [
      { url: "https://images.unsplash.com/photo-1596591603951-28b9355745a5?q=80&w=2834&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D", filename: "listing23_1.webp" },
    ],
    price: 150000000,
    location: "Mumbai",
    country: "India",
    purpose: "Sell",
    usage: "Commercial",
    propertyType: "Showroom",
    commercial: { size: 4000, parkingSpaces: 5, amenities: ["Central AC"] },
  },
  {
    title: "Service Apartment in Chennai",
    description: "Fully furnished service apartment with a kitchenette, ideal for business travelers and short stays.",
    image: [
      { url: "https://images.unsplash.com/photo-1590490359855-350b58e370a3?q=80&w=2787&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D", filename: "listing24_1.webp" },
    ],
    price: 3500,
    location: "Chennai",
    country: "India",
    purpose: "Rent",
    usage: "Hospitality",
    propertyType: "Service Apartment",
    hospitality: { rooms: 1, starRating: 4, amenities: ["WiFi", "Kitchen", "Security"] },
  },
  {
    title: "Eco-Friendly Treehouse Retreat",
    description: "Stay in an eco-friendly treehouse nestled in the forest. It's the perfect escape for nature lovers.",
    image: [
      { url: "https://images.unsplash.com/photo-1488462237308-ecaa28b729d7?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OXx8c2t5JTIwdmFjYXRpb258ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=800&q=60", filename: "listing25_1.webp" },
    ],
    price: 750,
    location: "Costa Rica",
    country: "Costa Rica",
    purpose: "Rent",
    usage: "Residential",
    propertyType: "Studio",
    residential: { size: 400, furnishing: "Furnished", amenities: ["WiFi"] },
  },
  {
    title: "Luxury Villa in the Maldives",
    description: "Indulge in luxury in this overwater villa in the Maldives with stunning views of the Indian Ocean.",
    image: [
      { url: "https://images.unsplash.com/photo-1439066615861-d1af74d74000?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8bGFrZXxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60", filename: "listing26_1.webp" },
    ],
    price: 6000,
    location: "Maldives",
    country: "Maldives",
    purpose: "Rent",
    usage: "Residential",
    propertyType: "Villa",
    residential: { size: 2500, furnishing: "Furnished", amenities: ["Pool", "WiFi"] },
  },
  {
    title: "Historic Brownstone in Boston",
    description: "Step back in time in this elegant historic brownstone located in the heart of Boston.",
    image: [
      { url: "https://images.unsplash.com/photo-1533619239233-6280475a633a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTR8fHNreSUyMHZhY2F0aW9ufGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60", filename: "listing27_1.webp" },
    ],
    price: 2200,
    location: "Boston",
    country: "United States",
    purpose: "Rent",
    usage: "Residential",
    propertyType: "Apartment",
    residential: { size: 1800, furnishing: "Unfurnished", amenities: ["Parking"] },
  },
];
const userIds = [
  "68aeef995f3fa37750471761",
  "68aeefb55f3fa37750471768",
  "68aeefcf5f3fa3775047176f",
];

const reviewComments = [
  "An absolutely unforgettable experience! The place was pristine and the views were breathtaking.",
  "Great location and very comfortable. The host was incredibly helpful. Highly recommend!",
  "A wonderful place to stay. It had everything we needed and more. We'll definitely be back.",
  "The property was exactly as described. Clean, modern, and in a perfect spot. Loved our stay!",
  "A truly magical getaway. The amenities were top-notch and the ambiance was perfect for a relaxing trip.",
];

module.exports = { data: sampleListings, userIds, reviewComments };